# Generated by Django 6.0.1 on 2026-02-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonials'),
        ('website', '0006_create_superuser'),
    ]

    operations = [
    ]
