# Generated by Django 6.0.1 on 2026-02-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactmessage_phone'),
        ('website', '0007_merge_0004_testimonials_0006_create_superuser'),
    ]

    operations = [
    ]
